name: build plugin

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/build-plugin.yml'
      - 'plugins/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Run build
        run: |
          ./gradlew plugin:build
